### PR TITLE
Add Go documents

### PR DESCRIPTION
**Pull request by fjl**
They might be helpful.

### CODE REVIEW

**Comment by subtly** [comment]
As discussed, can you create these as wiki documents?

I'll create issues for merging this content, extracting devp2p specs, documenting overall architecture, etc.

**Comment by subtly** [comment]
Are these up-to-date enough that I can place them in the wiki?

**Comment by fjl** [comment]
No.

**Comment by fjl** [comment]
I will update them later and ping you back.

**Pull request closed without merging**
